add magma and kuznetchik support for TLSTREE mode
gost-engine/engine pull request #293
Opened 2020-10-30 08:42 UTC by igrkir

add case 'EVP_CTRL_TLSTREE' in ctl function for magma and kuznetchik.
add some GOST tests in tlstree test.
remove OpenSSL3.0 dependencies.
modify gost cipher to store master key, used for TLSTREE mode.

remove projects, that depend on OpenSSL3.0.
add options to remove compiler 'const' errors.

2020-10-31 10:47 UTC, beldmit requested changes

2020-11-05 12:22 UTC, igrkir commented on gost_ec_keyx.c
> +    BIGNUM *scalar = NULL, *X = NULL, *Y = NULL, *order = NULL;
этот код из прошлой реализации (коммит dbc8f4780fa78d66a68174f78f9ae9aa9cdad53c от 08.06.2020), до того как была использована функция EC_GROUP_get0_field(grp) из ossl 3.0.
в обоих ветках не получится - в ossl 1.1.1 в API такой функции не предусмотрено.

2020-11-05 12:26 UTC, beldmit commented on gost_ec_keyx.c
> +    BIGNUM *scalar = NULL, *X = NULL, *Y = NULL, *order = NULL;
Ага, понял.

2020-11-05 13:44 UTC, igrkir commented on CMakeLists.txt
> +        # test_sign
да завязаны. в частности, для ossl 1.1.1:
для файле test_sign.c не не определена функция OSSL_STORE_attach(),
а для файла test_params.c ругается на функцию PEM_write_bio_X509_PUBKEY.

2020-11-05 14:12 UTC, alexspirtmsu commented on CMakeLists.txt
> +        # test_sign
Либо полностью убираем тест, либо можем откатиться на версию, когда не были использованы функции из ossl 3.0 8899117e7e6a71fe7aecefe0175e84e3a51cdc06

2020-11-05 14:32 UTC, vt-alt commented on CMakeLists.txt
> +        # test_sign
Можно/лучше за-#ifdef'ать эту часть (про store).

2020-11-06 19:59 UTC, beldmit commented on CMakeLists.txt
> +        # test_sign
Лучше за #ifdef--ить, но в крайнем случае комментарий сойдёт

2020-11-13 07:50 UTC, beldmit commented
Можете поправить .travis.yml и .cirrus.yml, чтобы сборка и тесты проходили автоматически? Эта ветка не соберётся без приложения патча к openssl и соответственно, тесты не пробегут.

2020-11-13 10:34 UTC, igrkir commented
правильно ли я понимаю, что сейчас :
.travis.yml собирается для openssl-3.0.0-alpha6, а
.cirrus.yml - для текущей ветки master, 
а нужно передеать эти скрипты для автоматической сборки с пропатченным OpenSSL версии OpenSSL_1_1_1g (commit e2e09d9fba) при помощи патча patches/openssl_111g.diff?

2020-11-13 10:37 UTC, beldmit commented
Да, правильно, а переделывать надо на OpenSSL-1.1.1-stable

2021-12-30 10:57 UTC, igrkir commented
ввиду принятия PR https://github.com/gost-engine/engine/pull/339 удалил лишнее.

2022-01-11 11:31 UTC, beldmit commented
Close/reopen to trigger checks

2022-01-11 11:36 UTC, merged

2022-01-11 11:36 UTC, beldmit commented
Merged. Many thanks!