Rewrite error handling in pub_decode_gost_ec()
gost-engine/engine pull request #356
Opened 2021-09-17 13:59 UTC by nyx191

Closes #126

2021-09-18 17:19 UTC, beldmit requested changes

2021-09-18 17:19 UTC, beldmit commented on gost_ameth.c
> +    if (pub_key)
Почти всё хорошо, но проверки в конструкциях  if (X) free(Х) не нужны

2021-09-19 07:43 UTC, nyx191 commented on gost_ameth.c
> +    if (pub_key)
> Почти всё хорошо, но проверки в конструкциях if (X) free(Х) не нужны

Спасибо за ревью. У меня возникло 2 вопроса по поводу выделения памяти в openssl.
1. Почему в самом коде не проверяется, не вернула ли BN_bin2bn() NULL? Как я понимаю, в BN_bin2bn() происходит выделение памяти с помощью BN_new()=>*zalloc().
2. Как Вы верно подметили, в BN_free() осуществляется проверка, нулевой ли аргумент функции, поэтому нашему коду проверку делать не обязательно. По этой же причине эта проверка не нужна в EC_POINT_free() и ASN1_OCTET_STRING_free() (последнюю я нашел только в доке). Выходит, проверка нужна только в OPENSSL_free(). Я не могу проследить здесь конкретной логики, разве что OPENSSL_free() это самая "низкоуровневая" функция. Может быть, проще избегать по возможности вызова лишних функций и не полагаться на их обработку NULL-аргумента, а просто выполнять проверки, благо они не усложняют функцию?

2021-09-19 08:05 UTC, vt-alt commented on gost_ameth.c
> +    if (pub_key)
Для `OPENSSL_free` тоже не нужна. Писать заведомо бесполезный код "на всякий случай" не рационально — так можно далеко зайти.

Проверять код возврата `BN_bin2bn` стоит — как минимум для verbosity, но `ec_GFp_simple_point_set_affine_coordinates` вернет ошибку если эти `BIGNUM` `NULL`.

2021-09-19 09:49 UTC, merged

2021-09-19 09:49 UTC, beldmit commented
Merged. Thanks!